spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.141.4:5432/product
    username: postgres
    password: dRakoXxt6Jwe8&ml
  jpa:
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: false
server:
  port: 8081